chain_name: corsika_snowstorm_prompt_v1_9_1
n_events_per_run: 100
n_runs: 10000

dataset_number: 30012
seed: 3

resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    0: 4gb
    1: 6gb
    2: 5gb
    3: 3gb
    4: 3gb
    5: 3gb
    12: 3gb
    13: 3gb
    14: 3gb
    15: 3gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus:

# -------------------------------
# Step 0: CORSIKA simprod.modules
# -------------------------------
corsika_module: 'icecube.simprod.modules.Corsika5ComponentGenerator'
corsika_settings: {

    # things that are probably fine like this most of the time
    'corsikaVersion': '77500',
    'CVMFS': '/cvmfs/icecube.opensciencegrid.org/users/pgutjahr/software/CORSIKA/',
    'model': 'sibyll',  
    'CutoffType': 'EnergyPerParticle',
    'oversampling': 1,
    'UsePipe': True,
    'polyplopia': True,
    'mctree_polyplopia': 'I3MCTree',
    'nuaddi': True,

    # Set Atmosphere
    'ratmo': -1, 
    'atmospheres': [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
    
    # energ cuts under which particles are not simulated
    'ecuts1': 273.,  # hadron min energy (see corsika docs)
    'ecuts2': 273.,  # muon min energy (see corsika docs)
    'ecuts3': 273.,  # electron min energy (see corsika docs)
    'ecuts4': 273.,  # photon min energy (see corsika docs)

    # things that should be defined by user:
    'eprimarymin': !!float 5e2,
    'eprimarymax': !!float 1e6,
    'pnorm': [10., 5., 3., 2., 1.],
    'pgam': [1., 1., 1., 1., 1.],
    'trimshower': True,
}

# Delete keys from the frame after step 0
step_0_delete_keys: [
  # 'I3MCTree_preSampling',
  # 'I3MCTree',
]

muon_propagation_config : {}


# -----------------------------
# Step 1: Snowstorm Propagation
# -----------------------------
NumEventsPerModel: 100
DOMOversizeFactor: 1.
UseI3PropagatorService: False
UseGPUs: True
SummaryFile:

# These arguments will be passed on to the CLSIM Client Module
ExtraArgumentsToI3CLSimClientModule:
  # Sources with no DOMs within this distance (meter) are *not* simulated
  ClosestDOMDistanceCutoff: 500.

# Snowstorm Configuration
snowstorm_config:
  # Config for the full-scale systematics dataset
  # (after alignment with the calibration group)
  # Link: https://wiki.icecube.wisc.edu/index.php/Ice_models
  # baseline ice-model and hole-ice parametrization
  IceModelLocation: "$I3_BUILD/ice-models/resources/models/ICEMODEL/spice_ftp-v3m"
  HoleIceParameterization: "$I3_BUILD/ice-models/resources/models/ANGSENS/angsens_unified/as.set50_p0=-0.27_p1=-0.042"
  # Control ice model perturbations:
  Perturbations:
      # IceWavePlusModes for depth dependent absorption/scattering scaling
      IceWavePlusModes:
          apply: False
          type: default
      # Global ice scattering scaling
      Scattering:
          type: uniform
          uniform:
              limits: [[0.913, 1.087]]
      # Global ice absorption scaling
      Absorption:
          type: uniform
          uniform:
              limits: [[0.913, 1.087]]
      # # Ice anisotropy scaling
      # # Note: no SnowStorm anisotropy parameter exists yet for SpiceFTP
      # AnisotropyScale:
      #     type: uniform
      #     uniform:
      #         limits: [[0., 2.0]]
      # DOM efficiency scaling
      DOMEfficiency:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]

      # DOM angular acceptance according to the Unified HoleIce model
      # see: https://github.com/philippeller/angular_acceptance
      # HoleIceForward_Unified:
      #     type: uniform
      #     uniform:
      #             limits: [[-0.5, 0.3], [-0.1, 0.05]]
      
      HoleIceForward_Unified_zdep:
          type: uniform
          uniform:
                  limits: [[-0.5, 0.3], [-0.1, 0.05], [-0.2, 0.2], [-0.05, 0.05]]
