chain_name: corsika_snowstorm_prompt_v1_5_1
n_events_per_run: 1000
n_runs: 10

dataset_number: 40011
seed: 2

corsika_module: 'icecube.simprod.modules.Corsika5ComponentGenerator'
corsika_settings: {

    # things that are pirobably fine like this most of the time
    'corsikaVersion': '77420',
    'model': 'SIBYLL',
    'CutoffType': 'EnergyPerParticle',
    'oversampling': 1,
    'trimshower': True,
    'pnorm': [10., 5., 3., 2., 1.],
    'pgam': [2., 2., 2., 2., 2.],
    'UsePipe': True,
    
    'ecuts1': 273.,  # hadron min energy (see corsika docs)
    'ecuts2': 273.,  # muon min energy (see corsika docs)
    'ecuts3': 273.,  # electron min energy (see corsika docs)
    'ecuts4': 273.,  # photon min energy (see corsika docs)
    # 'CVMFS': '/home/pgutjahr/simulation_scripts/pgutjahr_icesoft/corsika/',
    'CVMFS': '/data/user/pgutjahr/software/CORSIKA/',
    # 'tmpdir': '/data/user/pgutjahr/tmpdir/',
    # 'CVMFS': '/data/user/lneste/corsikas' ,
    # things that should be defined by user:
    'polyplopia': True,
    'mctree_polyplopia': 'I3MCTree',
    'eprimarymin': !!float 1e6,
    'eprimarymax': !!float 1e8,
    'nuaddi': True,
}
muon_propagation_config : {
#   'PROPOSAL_config_file': '/data/user/lwitthaus/configs/config_proposal.json',
    'PROPOSAL_config_file': '/data/user/pgutjahr/software/icetray/v1.5.0/src/PROPOSAL/resources/config_icesim.json',
}

UseGPUs: True

resources:
  # Indication which steps need GPUs, default is 0
  gpus:
    1: 1
  # Indication of needed memory for each step if nothing is set 1GB is assumed as default
  memory:
    0: 2gb
    1: 5gb
    2: 2gb
    3: 2gb
    4: 2gb
    5: 3gb
    12: 3gb
    13: 3gb
    14: 3gb
    15: 3gb
  # Indication of the walltime (in hours) for each step, if nothing is set the system default for dagman and 1h for pbs are assumed
  walltime:
  # Indication of the number of cores for each step, default is 1
  cpus: