chain_name: corsika_snowstorm_prompt
n_events_per_run: 100
n_runs: 10

dataset_number: 10220
seed: 4

corsika_module: 'icecube.simprod.modules.Corsika5ComponentGenerator'
corsika_settings: {

    # things that are pirobably fine like this most of the time
    'corsikaVersion': '77420',
    'model': 'SIBYLL',
    'CutoffType': 'EnergyPerNucleon',
    'oversampling': 1,
    'trimshower': False,
    'pnorm': [10., 5., 3., 2., 1.],
    'pgam': [1., 1., 1., 1., 1.],
    'UsePipe': True,
    
    'ecuts1': 273.,  # hadron min energy (see corsika docs)
    'ecuts2': 273.,  # muon min energy (see corsika docs)
    # 'ecuts3': 0.003,  # electron min energy (see corsika docs)
    # 'ecuts4': 0.003,  # photon min energy (see corsika docs)
    
    # 'ecuts1': !!float 1e3,  # hadron min energy (see corsika docs)
    # 'ecuts2': !!float 1e3,  # muon min energy (see corsika docs)
    'ecuts3': !!float 1e20,  # electron min energy (see corsika docs)
    'ecuts4': !!float 1e20,  # photon min energy (see corsika docs)
    # 'CVMFS': '/home/pgutjahr/simulation_scripts/pgutjahr_icesoft/corsika/',
    'CVMFS': '/data/user/pgutjahr/software/CORSIKA/',
    # 'tmpdir': '/data/user/pgutjahr/tmpdir/',
    # 'CVMFS': '/data/user/lneste/corsikas' ,
    # things that should be defined by user:
    'polyplopia': False,
    # 'mctree_polyplopia': 'I3MCTree',
    'eprimarymin': 600,
    'eprimarymax': !!float 1e6,
    'nuaddi': True,
}
muon_propagation_config : {
#   'PROPOSAL_config_file': '/data/user/lwitthaus/configs/config_proposal.json',
    'PROPOSAL_config_file': '/data/user/pgutjahr/software/icetray/v1.5.0/src/PROPOSAL/resources/config_icesim.json',
}

UseGPUs: True