chain_name: corsika_snowstorm_prompt
n_events_per_run: 10
n_runs: 1

dataset_number: 7356
seed: 3

corsika_module: 'icecube.simprod.modules.Corsika5ComponentGenerator'
corsika_settings: {

    # things that are pirobably fine like this most of the time
    'corsikaVersion': '77420',
    'model': 'SIBYLL',
    'CutoffType': 'EnergyPerNucleon',
    'oversampling': 1,
    'trimshower': True,
    'pnorm': [10., 5., 3., 2., 1.],
    'pgam': [2., 2., 2., 2., 2.],
    'UsePipe': True,

    'ecuts1': 273.,  # hadron min energy (see corsika docs)
    'ecuts2': 273.,  # muon min energy (see corsika docs)
    'ecuts3': 0.003,  # electron min energy (see corsika docs)
    'ecuts4': 0.003,  # photon min energy (see corsika docs)

    # 'ecuts1': !!float 1e3,  # hadron min energy (see corsika docs)
    # 'ecuts2': !!float 1e3,  # muon min energy (see corsika docs)
    # 'ecuts3': !!float 1e20,  # electron min energy (see corsika docs)
    # 'ecuts4': !!float 1e20,  # photon min energy (see corsika docs)
    # 'CVMFS': '/home/pgutjahr/simulation_scripts/pgutjahr_icesoft/corsika/',
    'CVMFS': '/data/user/pgutjahr/software/CORSIKA/',
    # 'tmpdir': '/data/user/pgutjahr/tmpdir/',
    # 'CVMFS': '/data/user/lneste/corsikas' ,
    # things that should be defined by user:
    'polyplopia': False,
    'eprimarymin': !!float 1e5,
    'eprimarymax': !!float 5e10,
    'nuaddi': True,
}
muon_propagation_config : {
    'PROPOSAL_config_file': '/data/user/lwitthaus/configs/config_proposal.json',
}

# -----------------------------
# Step 2: Detector Simulation
# -----------------------------
# keep MCPEs in frame
det_keep_mc_hits: False
# keep I3MCPulseSeriesMap in frame.
det_keep_mc_pulses: False
# Keep everything upto run X
det_pass2_keep_all_upto: -1
# keep MCTree with all in-ice propagated secondaries. These take a lot of space compared un propagated tree.
det_keep_propagated_mc_tree: True
# remove events that don't pass any trigger.
det_filter_trigger: False

UseGPUs: True
SummaryFile:
snowstorm_config:
  # Config for the full-scale systematics dataset
  # (after alignment with the calibration group)
  # baseline ice-model and hole-ice parametrization
  IceModelLocation: "$I3_BUILD/ice-models/resources/models/ICEMODEL/spice_bfr-v2"
  HoleIceParameterization: "$I3_BUILD/ice-models/resources/models/ANGSENS/angsens/as.flasher_p1_0.30_p2_-1"
  # Control ice model perturbations:
  Perturbations:
      # IceWavePlusModes for depth dependent absorption/scattering scaling
      IceWavePlusModes:
          apply: False
          type: default
      # Global ice scattering scaling
      Scattering:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]
      # Global ice absorption scaling
      Absorption:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]
      # Ice anisotropy scaling
      AnisotropyScale:
          type: uniform
          uniform:
              limits: [[1., 1.]] # Dummy AnisotropyScale perturbation
      # DOM efficiency scaling
      DOMEfficiency:
          type: uniform
          uniform:
              limits: [[0.9, 1.1]]

      # DOM angular acceptance according to the Unified HoleIce model
      # see: https://github.com/philippeller/angular_acceptance
      HoleIceForward_Unified:
          type: uniform
          uniform:
                  limits: [[-1., 1.], [-0.2, 0.2]]
